apiVersion: v1
kind: Secret
metadata:
  name: tombolo-jobs-secrets
  namespace: {{ include "tombolo.namespace" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.jobs.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
