{{- include "tombolo.validateRequiredSecrets" . }}
apiVersion: v1
kind: Secret
metadata:
  name: tombolo-runtime-secrets
  namespace: {{ include "tombolo.namespace" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.runtime.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
