apiVersion: v1
kind: Service
metadata:
  name: tombolo-server
  namespace: {{ include "tombolo.namespace" . }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: tombolo-server
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
