apiVersion: v1
kind: Secret
metadata:
  name: tombolo-server-secrets
  namespace: {{ include "tombolo.namespace" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.server.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
