version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/**"
    schedule:
      interval: "daily"
    target-branch: "dev" # Dependabot will scan the 'dev' branch
    allow:
      - dependency-type: "production"
