packages:
  - "Tombolo/server"
  - "Tombolo/client-reactjs"
  - "Tombolo/db"
  - "Tombolo/shared"
  - "Tombolo/jobs"
  - "e2e_tests"
  - "tombolo_docs"

catalog:
  axios: ^1.13.2
  lodash: ^4.17.21
  '@hpcc-js/comms': ^3.7.6
  dotenv: ^8.6.0
  mysql2: ^3.9.1
  prettier: ^3.5.3
  uuid: ^8.3.2
  sequelize: ^6.35.2
  nodemon: ^2.0.22
  typescript: ^5.9.3
  '@types/node': ^24.3.1
  typescript-eslint: ^8.46.2
  winston: ^3.18.3
  winston-daily-rotate-file: ^5.0.0
    
