packages:
  - Tombolo/server
  - Tombolo/client-reactjs
  - Tombolo/db
  - Tombolo/shared
  - Tombolo/core
  - Tombolo/jobs

catalog:
  '@hpcc-js/comms': ^3.12.0
  '@types/node': ^24.10.9
  '@vitest/coverage-v8': ^3.2.4
  axios: ^1.13.5
  dotenv: ^16.4.7
  express: ^5.2.1
  lodash: ^4.17.21
  mysql2: ^3.9.1
  nodemon: ^3.1.7
  prettier: ^3.5.3
  sequelize: ^6.35.2
  tsup: ^8.5.1
  typescript: ^5.9.3
  typescript-eslint: ^8.46.2
  uuid: ^8.3.2
  vitest: ^3.2.4
  winston: ^3.18.3
  winston-daily-rotate-file: ^5.0.0
