export const Constants = {
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILED: 'USERS_LOGIN_FAILED',
  LOGOUT_SUCCESS: 'USERS_LOGOUT',
  LOGOUT_FAILED: 'USERS_LOGOUT_FAILED',

  APPLICATION_SELECTED: 'APPLICATION_SELECTED',
  NEW_APPLICATION_ADDED: 'NEW_APPLICATION_ADDED',
  APPLICATION_UPDATED: 'APPLICATION_UPDATED',
  APPLICATION_DELETED: 'APPLICATION_DELETED',
  NO_APPLICATION_FOUND: 'NO_APPLICATION_FOUND',
  APPLICATION_LEFT_TOUR_SHOWN: 'APPLICATION_LEFT_TOUR_SHOWN',
  APPLICATION_ADD_BUTTON_TOUR_SHOWN: 'APPLICATION_ADD_BUTTON_TOUR_SHOWN',

  CLUSTERS_FOUND: 'CLUSTERS_FOUND',
  NO_CLUSTERS_FOUND: 'NO_CLUSTERS_FOUND',
  CLUSTERS_LEFT_TOUR_SHOWN: 'CLUSTERS_LEFT_TOUR_SHOWN',
  CLUSTERS_ADD_BUTTON_TOUR_SHOWN: 'CLUSTERS_ADD_BUTTON_TOUR_SHOWN',
  CLUSTER_SELECTED: 'CLUSTER_SELECTED',

  DATE_FORMAT_OPTIONS: { year: 'numeric', month: 'long', day: 'numeric' },
  COMPACT_DATE_FORMAT_OPTIONS: { year: 'numeric', month: 'numeric', day: 'numeric' },
  TIME_FORMAT_OPTIONS: { hour: '2-digit', minute: '2-digit' },

  TOMBOLO_ADMIN: 'Tombolo_Admin',
  TOMBOLO_READER: 'Reader',
  TOMBOLO_CREATOR: 'Creator',

  DATAFLOW_SELECTED: 'DATAFLOW_SELECTED',
  DATAFLOW_RESET: 'DATAFLOW_RESET',

  ASSET_SELECTED: 'ASSET_SELECTED',
  NEW_ASSET: 'NEW_ASSET',
  SEARCH_ASSET: 'SEARCH_ASSET',
  ASSET_SAVED: 'ASSET_SAVED',

  FETCH_GROUPS_TREE: 'FETCH_GROUPS_TREE',
  FETCH_GROUPS_TREE_SUCCESS: 'FETCH_GROUPS_TREE_SUCCESS',
  FETCH_GROUPS_TREE_ERROR: 'FETCH_GROUPS_TREE_ERROR',
  SELECT_GROUP: 'SELECT_GROUP',
  GROUPS_EXPANDED: 'GROUPS_EXPANDED',
  EMPTY_GROUPS_TREE: 'EMPTY_GROUPS_TREE',

  ASSET_IN_GROUP_SELECTED: 'ASSET_IN_GROUP_SELECTED',

  CONSUMERS_RETRIEVED: 'CONSUMERS_RETRIEVED',
  LICENSES_RETRIEVED: 'LICENSES_RETRIEVED',
  CONSTRAINTS_RETRIEVED: 'CONSTRAINTS_RETRIEVED',
  UPDATE_CONSTRAINTS: 'UPDATE_CONSTRAINTS',
  UPDATE_INTEGRATIONS: 'UPDATE_INTEGRATIONS',
  INTEGRATIONS_RETRIEVED: 'INTEGRATIONS_RETRIEVED',

  PROPAGATIONS_CHANGES_INITIATE: 'PROPAGATIONS_CHANGES_INITIATE',
  PROPAGATIONS_CHANGES_SUCCESS: 'PROPAGATIONS_CHANGES_SUCCESS',
  PROPAGATIONS_CHANGES_ERROR: 'PROPAGATIONS_CHANGES_ERROR',

  SET_BACKEND_STATUS: 'SET_BACKEND_STATUS',

  PROPAGATIONS_CURRENT_INITIATE: 'PROPAGATIONS_CURRENT_INITIATE',
  PROPAGATIONS_CURRENT_SUCCESS: 'PROPAGATIONS_CURRENT_SUCCESS',
  PROPAGATIONS_CURRENT_ERROR: 'PROPAGATIONS_CURRENT_ERROR',
  UPDATE_REPORTS: 'UPDATE_REPORTS',
};
