export const Constants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  LOGOUT: 'USERS_LOGOUT',
  VALIDATE_TOKEN: 'VALIDATE_TOKEN',
  VALIDATING_TOKEN: 'VALIDATING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

  APPLICATION_SELECTED: 'APPLICATION_SELECTED',
  NEW_APPLICATION_ADDED: 'NEW_APPLICATION_ADDED',
  APPLICATION_UPDATED: 'APPLICATION_UPDATED',
  APPLICATION_DELETED: 'APPLICATION_DELETED',

  DATE_FORMAT_OPTIONS: { year: 'numeric', month: 'long', day: 'numeric' },

  TOMBOLO_ADMIN: 'Tombolo_Admin',
  TOMBOLO_READER: 'Reader',
  TOMBOLO_CREATOR: 'Creator',

  DATAFLOW_INSTANCE_SELECTED: 'DATAFLOW_INSTANCE_SELECTED',

  DATAFLOW_SELECTED: 'DATAFLOW_SELECTED',
  DATAFLOW_RESET: 'DATAFLOW_RESET',

  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',

  ASSET_SELECTED: 'ASSET_SELECTED',
  NEW_ASSET: 'NEW_ASSET',
  SEARCH_ASSET: 'SEARCH_ASSET',
  ASSET_SAVED: 'ASSET_SAVED',

  FETCH_GROUPS_TREE: 'FETCH_GROUPS_TREE',
  FETCH_GROUPS_TREE_SUCCESS: 'FETCH_GROUPS_TREE_SUCCESS',
  FETCH_GROUPS_TREE_ERROR: 'FETCH_GROUPS_TREE_ERROR',
  SELECT_GROUP: 'SELECT_GROUP',
  GROUPS_EXPANDED: 'GROUPS_EXPANDED',
  EMPTY_GROUPS_TREE: 'EMPTY_GROUPS_TREE',

  ASSET_IN_GROUP_SELECTED: 'ASSET_IN_GROUP_SELECTED',

  UPDATE_ASSET_TABLE: 'UPDATE_ASSET_TABLE',

  CLUSTER_SELECTED: 'CLUSTER_SELECTED',
  CLUSTERS_RETRIEVED: 'CLUSTERS_RETRIEVED',

  CONSUMERS_RETRIEVED: 'CONSUMERS_RETRIEVED',
  ENABLE_EDIT: 'ENABLE_EDIT',
  ADD_ASSET: 'ADD_ASSET',
};
