const path = require("path");
const ejs = require("ejs");
const fs = require("fs");

const generateJobMonitoringMessageCardTable = (tableData) => {
  const templatePath = path.join(__dirname,"jobMonitoring_asr.ejs");
  const template = fs.readFileSync(templatePath, "utf-8");
  const table = ejs.render(template, tableData)
  return `${table}`
};

const teamsCardData = ({ data }) => {

  const tableString = generateJobMonitoringMessageCardTable(data);
  const cardData = {
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    summary:
      typeof data.monitoringName !== "undefined"
        ? `This alert is generated by ${data.monitoringName}`
        : "Job Monitoring Alert",
    sections: [
      {
        activityTitle:
          typeof data.monitoringName !== "undefined"
            ? `This alert is generated by ${data.monitoringName}`
            : "Job Monitoring Alert",
        activitySubtitle: "",
        activityImage: "",
        facts: [],
        markdown: true,
      },
      {
        startGroup: true,
        text: tableString,
      },
    ],
  };
  return cardData;
};

module.exports = { teamsCardData };
