const generateJobMonitoringMessageCardTable = (tableData) => {
  return `
  <table >
    <tbody>
      <tr>
        <td style="padding: 10px;"><strong>Notification ID</strong></td>
        <td>${
          typeof tableData.notificationId !== "undefined"
            ? notificationId
            : "NA"
        }</td>
      </tr>
      <tr>
        <td style="padding: 10px;"><strong>Product</strong></td>
        <td>${typeof tableData.product !== "undefined" ? product : "NA"}</td>
      </tr>
      <tr>
        <td style="padding: 10px;"><strong>Issue</strong></td>
        <td>${typeof tableData.issue !== "undefined" ? issue : "NA"}</td>
      </tr>
      <tr>
        <td style="padding: 10px;"><strong>Severity Code</strong></td>
        <td>${typeof tableData.severity !== "undefined" ? severity : "NA"}</td>
      </tr>
      <tr>
        <td style="padding: 10px;"><strong>First Logged</strong></td>
        <td>${
          typeof tableData.firstLogged !== "undefined" ? firstLogged : "NA"
        }</td>
      </tr>
      <tr>
        <td style="padding: 10px;"><strong>Last Logged</strong></td>
        <td>${
          typeof tableData.lastLogged !== "undefined" ? lastLogged : "NA"
        }</td>
      </tr>
      <tr>
        <td style="padding: 10px;"><strong>Remedy</strong></td>
        <td>
          Please contact one of the following to facilitate issue resolution:
          <ul>
            <li>Primary: ${
              typeof tableData.primaryContact !== "undefined"
                ? tableData.primaryContact
                : "NA"
            }</li>
            <li>Secondary: ${
              typeof tableData.secondaryContact !== "undefined"
                ? tableData.secondaryContact
                : "NA"
            }</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td style="padding: 10px;"><strong>Region</strong></td>
        <td>${typeof tableData.region !== "undefined" ? region : "NA"}</td>
      </tr>
      <tr>
        <td style="padding: 10px;"><strong>Business Unit</strong></td>
        <td>${
          typeof tableData.businessUnit !== "undefined" ? businessUnit : "NA"
        }</td>
      </tr>
    </tbody>
  </table>`;
};

const teamsCardData = ({ data }) => {
  const tableString = generateJobMonitoringMessageCardTable((data = {}));
  const cardData = {
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    summary:
      typeof data.monitoringName !== "undefined"
        ? `This alert is generated by ${data.monitoringName}`
        : "Job Monitoring Alert",
    sections: [
      {
        activityTitle:
          typeof data.monitoringName !== "undefined"
            ? `This alert is generated by ${data.monitoringName}`
            : "Job Monitoring Alert",
        activitySubtitle: "",
        activityImage: "",
        facts: [],
        markdown: true,
      },
      {
        startGroup: true,
        text: tableString,
      },
    ],
  };
  return cardData;
};

module.exports = teamsCardData;
