server:
  secret:
    JWT_SECRET: "replace-me"
    JWT_REFRESH_SECRET: "replace-me"
    CSRF_SECRET: "replace-me"
    ENCRYPTION_KEY: "replace-me"
    JOBS_API_KEY: "replace-me"
    AKEYLESS_ACCESS_ID: "replace-me"
    AKEYLESS_ACCESS_KEY: "replace-me"
    TENANT_ID: ""
    CLIENT_ID: ""
    CLIENT_SECRET: ""
    REDIRECT_URI: ""
    EMAIL_SMTP_HOST: ""
    EMAIL_PORT: ""
    EMAIL_SENDER: "donotreply@tombolo.com"
    EMAIL_USER: ""
    EMAIL_PASS: ""

jobs:
  secret:
    JOBS_API_KEY: "replace-me"

runtime:
  secret:
    DB_USERNAME: "replace-me"
    DB_PASSWORD: "replace-me"
    REDIS_PASSWORD: "replace-me"
    REDIS_USER: ""
