name: Deploy Docusaurus Site to GitHub Pages

on:
  push:
    branches:
      - main
      - dev
      - yadhap/fix-doc-site-deployment
      - yadhap/docs-deployment-issue
    # paths:
    #   - "doc/**" # Only trigger if changes are in the doc directory

  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus Site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc # Set working directory to the doc folder
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Docusaurus site
        run: yarn build
        env:
          # Ensure the build output is in doc/build
          BUILD_PATH: build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build # Path to the Docusaurus build output

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
