name: Docker Compose ASR 
 
on:
  push:
    branches: [ASR-Deploy]

jobs:
  deploy:
    runs-on: [self-hosted, ASR]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to project directory and deploy
        run: |
          cd ~/Tombolo/Tombolo
          git checkout ASR-Deploy
          git stash
          git pull
          git stash apply
          sudo docker-compose down
          sudo docker-compose build
          sudo docker-compose up -d
