name: Deploy Docusaurus Site to GitHub Pages

on:
  push:
    branches:
      - main
      - dev
      - yadhap/fix-doc-site-deployment
      - yadhap/docs-deployment-issue
    paths:
      - "doc/**"
  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus Site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug - Check for package-lock.json
        run: ls -la package-lock.json || echo "No package-lock.json in doc"
      - name: Debug - Check for yarn.lock
        run: ls -la yarn.lock || echo "No yarn.lock in doc"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm # Use npm caching
      - name: Install dependencies
        run: npm ci # Use npm ci for CI environments
      - name: Build Docusaurus site
        run: npm run build # Use npm for consistency
        env:
          BUILD_PATH: build
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
