name: Docker Compose

on:
  push:
    branches: [yadhap/cicd, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd Tombolo/Tombolo
            git stash
            git pull
            git stash apply
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose up -d
