name: Build & Deploy to DEV 
on: 
  push:
      branches:
        - dev
  workflow_dispatch:      

env:
  PORT: ${{ secrets.PORT }}
  WEB_PORT: ${{ secrets.WEB_PORT }}
  WEB_EXPOSED_PORT: ${{ secrets.WEB_EXPOSED_PORT }}
  WEB_EXPOSED_HTTP_PORT: ${{ secrets.WEB_EXPOSED_HTTP_PORT }}
  PROXY_URL: ${{ secrets.PROXY_URL }}
  HOST_HOSTNAME: ${{ secrets.HOST_HOSTNAME }}
  WEB_URL: ${{ secrets.WEB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
  AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
  AUTHSERVICE_TOMBOLO_CLIENT_ID: ${{ secrets.AUTHSERVICE_TOMBOLO_CLIENT_ID }}
  REACT_APP_PROXY_URL: ${{ secrets.REACT_APP_PROXY_URL }}
  secret: ${{ secrets.secret }}
  AZURE_WEBAPP_PACKAGE_PATH: './client-reactjs/build'
  AZURE_WEBAPP_PACKAGE_PATH_API: './server'
  JOB_COMPLETE_GROUP_ID: 'tombolo_dev'

jobs:    
  build-ui:
    name: build-ui
    runs-on: self-hosted    
    #environment:
      #name: 'DEV'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        CI=false && npm run build --if-present
      working-directory: client-reactjs  
        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'tomboloui2-eastus2-dev'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
  build-api:
    name: build-api
    runs-on: self-hosted
    #environment:
      #name: 'DEV'
    steps:
    - uses: actions/checkout@main
    
    - name: Create cluster-whitelist
      run: |
        touch cluster-whitelist.js
        echo ${{ secrets.CLUSTER_WHITE_LIST }} >> cluster-whitelist.js
      working-directory: server
      
    - name: create env file
      run: |
        touch .env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_HOSTNAME=${{ secrets.DB_HOSTNAME }} >> .env
        echo AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }} >> .env
        echo AUTHSERVICE_TOMBOLO_CLIENT_ID=${{ secrets.AUTHSERVICE_TOMBOLO_CLIENT_ID }} >> .env
        echo ALGORITHM=${{ secrets.ALGORITHM }} >> .env
        echo IV_LENGTH=${{ secrets.IV_LENGTH }} >> .env
        echo ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }} >> .env
        echo secret=${{ secrets.secret }} >> .env
      working-directory: server
      
    - name: Print env
      run: |
        less .env
      working-directory: server
      
        
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
      working-directory: server
      
    - name: dbmigrate
      run: |
        npx sequelize-cli db:migrate        
      working-directory: server   
    
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'tomboloapi-eastus2-dev'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_API }}    
